### ISSUE TITLE
Error in Anki 2.1.20beta2

### ISSUE THREAD

**Issue by ghost** [Arthur-Milchior/anki-better-card-generation#1]
Anki throws the following error at boot.
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Improve speed of change of note type':
Traceback (most recent call last):
  File "aqt\addons.py", line 175, in loadAddons
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\115825506\__init__.py", line 1, in <module>
    from . import render
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\115825506\render.py", line 1, in <module>
    from anki.template.template import Template, get_or_attr, modifiers
ModuleNotFoundError: No module named 'anki.template.template'; 'anki.template' is not a package

**Comment by Arthur-Milchior** [comment]
Thank you very much for letting me know.
Currently, I have not been able to succesfully start anki's beta. So I can't test and correct it, sorry. I'm on linux. I don't know whether it's easier on windows, but anyway I can't correct right now. And being able to run the beta is not my priority

**Comment by ghost** [comment]
No problem. Just wanted to give you a heads up.

**Comment by Arthur-Milchior** [comment]
You're very welcome.
I've added a note in readme considering this problem. And a note in ankiweb to state that this add-on is compatible only up to 19
Given the way anki changed, I don't even know whether this add-on is still useful honestly. So I may just let it die. It has never been a success anyway
